stages:
  - test
  - package

default:
  image: alpine/helm:3.12.1
  tags:
    - kubernetes

variables:
  HELM_REPO_USERNAME: $HELM_REPO_USERNAME
  HELM_REPO_PASSWORD: $HELM_REPO_PASSWORD

test_chart:
  stage: test
  script:
    - helm repo add desy-it https://charts.desy.de/desy-it
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm dependency build helm/privacyidea
    - helm lint helm/privacyidea --values TestValues.yaml

package_chart:
  only:
    - main
  stage: package
  script:
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - helm repo add desy-it https://charts.desy.de/desy-it
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm dependency build helm/privacyidea
    - helm cm-push helm/privacyidea/ desy-it
