{{- if not .Values.privacyidea.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacyidea.fullname" .}}-admin-account-config
  labels:
{{ include "privacyidea.labels" . | indent 4 }}
type: Opaque
data:
  PRIVACYIDEA_ADMIN_USER: {{ .Values.privacyidea.admin.user | b64enc | quote}}
  PRIVACYIDEA_ADMIN_PASSWORD: {{  required "privacyidea.admin.password must be provided" .Values.privacyidea.admin.password | b64enc | quote }}
{{- end }}
