{{- if not .Values.privacyidea.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacyidea.fullname" .}}-dbsecret
  labels:
{{ include "privacyidea.labels" . | indent 4 }}
type: Opaque
data:
  user: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  password: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  dbname: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  host: {{ include "privacyidea.postgresql.fullname" . | b64enc | quote }}
  port: {{ .Values.postgresql.service.port | toString | b64enc | quote }}
{{- end }}
