{{- if not .Values.privacyidea.admin.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "privacyidea.fullname" .}}-dbsecret
  labels:
{{ include "privacyidea.labels" . | indent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  DB_PASS: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  DB_NAME: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  DB_HOST: {{ include "privacyidea.postgresql.fullname" . | b64enc | quote }}
  DB_PORT: {{ .Values.postgresql.primary.service.ports.postgresql | toString | b64enc | quote }}
{{- end }}
