apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "privacyidea.fullname" . }}
  labels:
    {{- include "privacyidea.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "privacyidea.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "privacyidea.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "privacyidea.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
    {{- if not .Values.skipInitContainers }}
      initContainers:
        {{- if .Values.postgresql.enabled }}
        - name: pgchecker
          image: "{{ .Values.pgchecker.image.repository }}:{{ .Values.pgchecker.image.tag }}"
          imagePullPolicy: {{ .Values.pgchecker.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.pgchecker.securityContext | nindent 12 }}
          command:
            - sh
            - -c
            - |
              echo 'Waiting for PostgreSQL to become ready...'
              until printf "." && nc -z -w 2 {{ include "privacyidea.postgresql.fullname" . }} {{ .Values.postgresql.service.port }}; do
                  sleep 2;
              done;
              echo 'PostgreSQL OK ✓'
          resources:
            {{- toYaml .Values.pgchecker.resources | nindent 12 }}
        {{- end }}
        - name: {{ .Chart.Name }}-init
          image: "{{ .Values.initImage.repository }}:{{ .Values.initImage.tag | default .Chart.AppVersion }}"
          command: 
            - /bin/bash 
            - /etc/privacyidea/config/init.sh
          volumeMounts:
            - name: config-volume
              mountPath: "/etc/privacyidea/config/"
            - name: key-volume
              mountPath: "/etc/privacyidea/secrets/"
          env:
          - name: PRIVACYIDEA_CONFIGFILE
            value: /etc/privacyidea-config/pi.cfg
          - name: DB_CONN
            value: {{ include "privacyidea.sqlstring" . | quote }}
          - name: DB_HOST
            valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: host } }
          - name: DB_PORT
            valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: port } }
          - name: DB_NAME
            valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: dbname } }
          - name: DB_USER
            valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: user } }
          - name: DB_PASS
            valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: password } }
          envFrom:
          - secretRef:
              name: {{ include "privacyidea.adminsecret" . }}
        {{- with .Values.extraInitContainers }}
        {{- tpl . $ | nindent 8 }}
        {{- end }}
    {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: "/etc/privacyidea/config"
          - name: key-volume
            mountPath: "/etc/privacyidea/secrets"
          env:
            - name: PRIVACYIDEA_CONFIGFILE
              value: /etc/privacyidea/config/pi.cfg
            - name: DB_CONN
              value: {{ include "privacyidea.sqlstring" .}}
            - name: DB_HOST
              valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: host } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: port } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: dbname } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: user } }
            - name: DB_PASS
              valueFrom: { secretKeyRef: { name: {{ include "privacyidea.dbsecret" .}}, key: password } }
          ports:
            - name: wsgi
              containerPort: 3031
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: wsgi
          readinessProbe:
            httpGet:
              path: /
              port: wsgi
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "privacyidea.fullname" .}}-config
        - name: key-volume
          persistentVolumeClaim:
          {{- if .Values.privacyidea.persistence.existingClaim }}
            claimName: {{ .Values.privacyidea.persistence.existingClaim }}
          {{- else}}
            claimName: {{ include "privacyidea.fullname" .}}-pvc
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
